### ISSUE TITLE
Deploying separate Azure Functions with separate Virtual Networks fails in same Subscription

### ISSUE THREAD

**Issue by plamber** [Azure-Samples/azure-functions-flex-consumption-samples#38]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I am not sure if this is a bug or if I missed some prerequisites.

We are developing several solutions that utilize Azure Functions Flexconsumption with VNET integration, all within the same subscription. Each solution consists of a dedicated Azure Function with its own VNET, and these solutions are not interconnected. The deployment of the first solution proceeds without any issues. Similarly, the initial deployment of the second solution is successful. However, any attempt to redeploy the second solution fails, returning the error: "The new SKU does not support Regional VNET integration which some apps are still using. Please disconnect apps from Regional VNET integration and try again."

Is there a limitation that requires me to have different subscriptions to handle this use case? Our aim is to have a microservice architecture with all solutions having their own VNET integration and being separated from the rest networkwise.

### Minimal steps to reproduce
In the same solution
- Create a solution with Azure Function Flexconsumption + VNET Integration
- Create a second solution with Azure Function Flexconsumption + VNET Integration
- Deploy both solutions
- Deploy the second solution, you will recieve the error "The new SKU does not support Regional VNET integration which some apps are still using. Please disconnect apps from Regional VNET integration and try again."

### Expected/desired behavior
I can deploy multiple Azure Functions Flexconsumption with their dedicated VNET integration.

**Comment by nzthiago** [comment]
Thank you for reporting @plamber - we identified that a configuration change inadvertently caused this behavior. We mitigated this, so please try again. A permanent fix is rolling out in the next few weeks, but until it does please let us know if this reoccurs.

**Comment by plamber** [comment]
Thank you. I will try it out and come back to you in case it is not working

**Comment by nzthiago** [comment]
@plamber  - checking in on this one, want to ensure this is not a blocker for you to continue your testing of Flex Consumption, thank you.

**Comment by plamber** [comment]
Hi @nzthiago,
thank you for reaching out. I was able to deploy two functions without issues. The problem seems to be solved

Thank you
