### ISSUE TITLE
IaC Bicep: Storage Authentication in Function App Config isn't Applied Correctly

### ISSUE THREAD

**Issue by dsdilpreet** [Azure-Samples/azure-functions-flex-consumption-samples#45]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Clone this repo
Switch to Bicep directory
Provide all the parameters
Run the provided command in readme to deploy

### Any log messages given by the failure
> No, deployment succeeded.

### Expected/desired behavior
> Authentication Type in Function App Deployment Settings should be selected but it isn't.
![image](https://github.com/user-attachments/assets/962d2b7e-6cf8-40bd-ae65-1ab93665bec4)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11
### Versions
> Bicep CLI version 0.31.92

### Mention any other details that might be useful
I noticed that when we manually select an authentication type from Azure Portal and then export the template, the case of type value changes to pascal case whereas it is lowercase when deployed using bicep script even if the case in Bicep file is pascal.

![image](https://github.com/user-attachments/assets/26ec721d-092a-4f17-b0d4-a02bca61a3bc)

We have also tried using StorageAccountConnectionString authentication type and setting storageAccountConnectionStringName in bicep but it shows the same behaviour.

This is in `australiaeast` region.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dsdilpreet** [comment]
I tried again yesterday and it seems to be working now without any change. Not sure what happened there, maybe a backend issue somewhere. Closing for now.

**Comment by nzthiago** [comment]
Thank you - sorry I missed replying to this one @dsdilpreet - we indeed fixed an issue where the casing differences were causing the portal not to render the identity accurately. The storage auth did get applied correctly but the portal didn't show it correctly, and we fixed that.
